In [1]:
import numpy as np

# Mutidimensional Array

>**initializing a 0 dimensional array**

In [5]:
array =np.array('A')
print(array.ndim)

0


>**initializing a 1 dimensional array**

In [4]:
array =np.array(['A','B','C'])
print(array.ndim)

1


>**initializing a 2 dimensional array**

In [6]:
array =np.array([['A','B','C'],
                 ['D','E','F'],
                 ['G','H','I']])
print(array.ndim)

2


>**initializing a 3 dimensional array**

In [11]:
array =np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                 [['A','B','C'],['D','E','F'],['G','H','I']],
                 [['A','B','C'],['D','E','F'],['G','H','I']]])
print(array.ndim)
print(array.shape) # the output will be 3,3,3, first 3 represents the layers, the second rows and the third columns

3
(3, 3, 3)


>**how to access elements**

In [14]:
print(array[0][0][0])# this will return A, this is how we access array elements in python using chain indexing

#this is how its done in numpy
print(array[0,0,0])

A
A


>**Concatenating in numpy**

In [16]:
 word = array[0,0,0] + array[0,2,2] + array[0,0,0]
 print(word)

AIA


# Slicing in numpy

In [19]:
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

**in numpy the syntax for slicing is array[start:end:step]**


>**Row Operations**

In [27]:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [28]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


>**Columns Operations**

In [37]:
print(array[:,2])#prints the index 2 column in reverse

[ 3  7 11 15]


In [40]:
print(array[:,1:4])# skipping the first column and printing the rest

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [43]:
print(array[:,1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


# Arithmetic

>**scalar arithmetic**

In [50]:
array=np.array([1,2,3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array/4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [51]:
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [52]:
print(np.pi)

3.141592653589793


>**Vectorized Math Funcs**

In [54]:
radii=np.array([1,2,3])

In [55]:
#finding area of a circle
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


>**Element wise arethmetic**

In [56]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

print(array1+array2)
print(array1 - array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


>**Comparing Operators**

In [57]:
scores=np.array([91,55,100,73,82,64])

In [58]:
print(scores==100)

[False False  True False False False]


In [60]:
print(scores>=60)

[ True False  True  True  True  True]


# Aggregate Functions

In [62]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))#position of max number

5.5
2.8722813232690143
8.25
1
10
0
9


# Filtering

In [66]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], [39, 22, 15, 99, 18, 19, 20, 21]])
teenagers = ages [ages < 18]
print(teenagers)
adults=ages[(ages>=18) & (ages<65)]
print(adults)
seniors=ages[(ages>=65)]
print(seniors)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
